services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - database

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: asdasd
      MYSQL_DATABASE: displayboard
      MYSQL_USER: user
      MYSQL_PASSWORD: asdasd
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge